import { ReactNode } from 'react';
import type { Metadata } from 'next';
import './globals.css';

import StoreProvider from './StoreProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <StoreProvider>
        <body className={`h-full flex flex-col`}>
          <main className="flex-1 flex flex-col">{children}</main>
        </body>
      </StoreProvider>
    </html>
  );
}
